version: '3.7'
services:
# List of services
  redis_storage:
    container_name: redis-local
    restart: always
    image: redis:alpine
    
    # Map the ports | bind to localhost
    ports:
     - '127.0.0.1:6374:6374'

    # Set up a dedicated network
    networks:
     - moodli

  main_app: 
    container_name: moodli
    env_file: docker.env
    restart: always
    # Directory of the dockerfile
    build: .
    # Name of the image, not the image to pull
    image: ${IMAGE_NAME}
    # Map the ports | bind to localhost
    ports:
      - '80:3003'
    #  Link it to another service
    depends_on:
      - redis_storage
    # Set env vars
    environment:
      - REDIS_HOST=redis-local
      - PORT=3003
      - NODE_ENV=production

    # Set up a dedicated network
    networks:
      - moodli

# Define the network type
networks:
  moodli:
    driver: bridge