const wordDict = {
  "aren't": 'are not',
  'arent': 'are not',
  "can't": 'cannot',
  'cant': 'cannot',
  "couldn't": 'could not',
  'couldnt': 'could not',
  "didn't": 'did not',
  'didnt': 'did not',
  "doesn't": 'does not',
  'doesnt': 'does not',
  "don't": 'do not',
  'dont': 'do not',
  "hadn't": 'had not',
  'hadnt': 'had not',
  'hasnt': 'has not',
  "hasn't": 'has not',
  "haven't": 'have not',
  'havent': 'have not',
  "he'd": 'he would',
  "he'll": 'he will',
  "he's": 'he is',
  'hes': 'he is',
  "i'd": 'I would',
  "i'll": 'I will',
  "i'm": 'I am',
  "isn't": 'is not',
  'isnt': 'is not',
  "it's": 'it is',
  "it'll": 'it will',
  "i've": 'I have',
  "let's": 'let us',
  "mightn't": 'might not',
  "mustn't": 'must not',
  "shan't": 'shall not',
  "she'd": 'she would',
  "she'll": 'she will',
  "she's": 'she is',
  'shes': 'she is',
  "shouldn't": 'should not',
  'shouldnt': 'should not',
  "that's": 'that is',
  'thats': 'that is',
  'dats': 'that is',
  'dat': 'that',
  'chink': 'chinese',
  "there's": 'there is',
  'theres': 'there is',
  "they'd": 'they would',
  "they'll": 'they will',
  "they're": 'they are',
  "they've": 'they have',
  "we'd": 'we would',
  "we're": 'we are',
  "weren't": 'were not',
  "we've": 'we have',
  "what'll": 'what will',
  "what're": 'what are',
  "what's": 'what is',
  'whats': 'what is',
  "what've": 'what have',
  "where's": 'where is',
  "who'd": 'who would',
  "who'll": 'who will',
  "who're": 'who are',
  "who's": 'who is',
  'whos': 'who is',
  "who've": 'who have',
  "won't": 'will not',
  'wont': 'will not',
  "wouldn't": 'would not',
  'wouldnt': 'would not',
  "you'd": 'you would',
  "you'll": 'you will',
  "you're": 'you are',
  "you've": 'you have',
  "'re": ' are',
  "wasn't": 'was not',
  "we'll": ' will',
  'luv': 'love',
  'usa': 'US',
  'rt': ''

};

module.exports = wordDict;
